<h4>Técnico Superior en Administración General</h4>
<h6>Resolución de la Carrera - Plan de estudio</h6>

<p>El Técnico Superior en Administración es aquel que esta preparado para un desempeño profesional en el ámbito de las empre-sas u organizaciones con una profesionalización técnica totalmente integrada. Es aquel que es capaz de utilizar las herramien-tas existentes en la organización y hacerlas funcionar eficaz y eficientemente, como así también es el innovador de nuevas estrategias para lograr un mejor desempeño de la administración de la empresa u organización. Es imprescindible que la formación de este profesional adquiera las capacidades para adaptarse a los cambios constantes del sistema productivo, con un perfil creativo e innovador y con mentalidad de trabajo en equipo. Los Técnicos Superiores en Administración se encontraran capacitados para desenvolverse en las siguientes áreas de compe-tencias: organizar, programar, ejecutar y controlar en las áreas de desarrollo de Dirección y planeamiento, Producción, Recursos Humanos, Compras, Ventas, Comercialización, Financiación, Contabilización, Gestión integral, dentro de los distintos tipos organizacionales Actuar de acuerdo con los códigos de comportamiento social, empresarial y legal, adoptando las normas éticas y morales que la función exige y comprender las diferentes formas que adopta la actividad en los diferentes países Utilizar correctamente razonamientos inductivos, deductivos y analógicos que faciliten la resolución de conflictos. Por medio de la fundamentación científica en los procesos y sistemas tecnológicos.</p>

<h6>Perfil Profesional</h6>
<p>El Técnico Superior en Administración es un profesional que estará capacitado para desarrollar las competencias para: organi-zar, programar, ejecutar y controlar las operaciones comerciales, financieras y administrativas de la organización; elaborar, controlar y registrar el flujo de información; organizar y planificar los recursos referidos para desarrollar sus actividades interac-tuando con el entorno y participando en la toma de decisiones relacionadas con sus actividades. Coordinando equipos de traba-jo relacionado con su especialidad. Estas competencias serán desarrolladas según las incumbencias y las normas técnicas y legales que rigen su campo profesional.</p>

<h6>Areas de Competencia</h6>
<p>Las áreas de competencia del Técnico Superior en Administración son las siguientes: 1. Organizar, programar, las operaciones comerciales, financieras y administrativas de la organización. 2. Ejecutar y controlar las operaciones comerciales, financieras y administrativas de la organización. 3. Elaborar, controlar y registrar el flujo de información. 4. Planificar los recursos requeridos para desarrollar sus actividades de la organización 5. Gestionar las decisiones relacionadas con sus actividades.</p>