<h4>Técnico Superior en Instalación y Mantenimiento de Sistemas de Cómputo</h4>
<h6>Resolución de la Carrera - Plan de estudio</h6>


<p>
Las computadoras y, en particular, la informática, como procesamiento automático de la información, se instauraron en la comunidad hace ya largo tiempo. Este fenómeno socio-tecnológico ha logrado que las organizaciones trabajen en forma más eficiente, analizando situaciones variables, ajustando los costos para obtener mayores beneficios y así, adaptar su organización al contexto. Los profesionales en Técnico Superior en Instalación y Mantenimiento de Sistemas de Cómputo podrán desempe&ntilde;arse en relación de dependencia en todo tipo de empresas que requieran una persona o grupo de personas que conduzcan el servicio de mantenimiento y soporte operativo interno y/o conducir grupos de trabajo en estas áreas. En forma independiente, actuando como consultor y/o contratista, para la realización de proyectos relacionados con la instalación, ampliación o adecuación de sistemas de cómputo y sus instalaciones auxiliares.
</p>
<h6>Perfil Profesional</h6>
<p>
El/la Técnico/a Superior en Instalación y Mantenimiento de Sistemas de Cómputo tendrá competencia para diagnosticar fallas y necesidades de instalaciones existentes como así también proyectar en forma integral nuevas instalaciones, realizando el mantenimiento preventivo y correctivo tanto en el campo como en laboratorio. Además tendrá competencia para: presupuestar, planificar, gestionar, instalar, poner en servicio y mantener sistemas de cómputo y sus instalaciones auxiliares acordes a las organizaciones que lo requieran; brindar asistencia técnica a los usuarios de dichos sistemas; garantizar la calidad de las instalaciones de acuerdo a las normas vigentes y ofrecer a los usuarios las alternativas más convenientes para aprovechar la evolución tecnológica como ventaja competitiva. Estas competencias serán desarrolladas según las normas técnicas, legales y éticas que rigen el campo profesional.
</p>
<h6>Areas de Competencia</h6>
<p>Estas áreas requieren del/a técnico/a superior el dominio de un saber hacer complejo en el que se movilizan conocimientos, valores, actitudes y habilidades de carácter tecnológico, social y personal que definen su identidad profesional. Ejecutar, presupuestar y/o planificar instalaciones de computadoras y redes de computadoras, software y sus instalaciones auxiliares. Gestionar los recursos, actividades y servicios del mantenimiento dentro de la organización. Mantener preventiva y/o correctivamente CPU´s, periféricos, redes y sus instalaciones auxiliares de provisión de energía. Asesorar a las organizaciones y a los usuarios acerca de las distintas normas vigentes en cuanto a instalación y operación de equipos de cómputo y su seguridad operacional. Capacitar y asistir a los usuarios acerca del manejo y operación de los equipos y software, y resolver los problemas afines a la explotación de los mismos.</p>