<h4>Técnico Superior en Turismo</h4>
<h6>Resolución de la Carrera - Plan de estudio</h6>


<p>
Este profesional debe estar capacitado para comprender la Actividad Turística como un todo y conocer los impactos sociales, culturales, económicos, y ambientales, de modo tal que su quehacer contribuya al desarrollo del país formulando, evaluando y desarrollando proyectos de nuevos productos de acuerdo al mercado local y cumpliendo la legislación correspondiente. El técnico superior en turismo estará en condiciones de generar, liderar, gestionar y organizar emprendimientos turísticos tanto en el ámbito público como en el privado, ejecutando tareas técnicas, estratégicas y operativas en ambos ámbitos. Debe actuar de acuerdo con los códigos de comportamiento social, empresarial y legal, adoptando las normas éticas y morales que la función exige y comprender las distintas formas que adopta la actividad en los diferentes países. Este técnico tiene que utilizar correctamente razonamientos inductivos, deductivos y analógicos que faciliten la resolución de conflictos, por medio de la fundamentación científica en los procesos y sistemas tecnológicos.
</p>
<h6>Perfil Profesional</h6>
<p>
El Técnico Superior en Turismo estará capacitado para comprender la actividad turística como un todo, conociendo sus diferen-tes impactos sociales, culturales, económicos y ambientales, para que sea un motor de desarrollo del País, dando respuestas a las diferentes necesidades, mediante el aprovechamiento integral de los recursos, naturales y culturales; potenciando la activi-dad, a través de un proceso participativo con los distintos actores sociales intervinientes, en la formulación, evaluación y desa-rrollo de planes, programas y proyectos turísticos. Estará capacitado para actuar como Profesional responsable en una Empresa de Viajes y Turismo de acuerdo con la normativa vigente, mediante su aval en el desempeño de las actividades turísticas.
</p>
<h6>Areas de Competencia</h6>
<p>
    Las áreas de competencia del Técnico Superior en Turismo son las siguientes: 1. Diagnosticar diseñar, liderar, gestionar, organizar emprendimientos turísticos en el ámbito público y privado. 2. Programar, organizar y coordinar productos turísticos y recreacionales, nacionales e internacionales. 3. Administrar, contratar e intermediar la venta de todo tipo de servicios turísticos o prestaciones de servicios turísticos satis-faciendo las necesidades de la demanda. 4. Elaborar, implantar y operar sistemas de información y de procesos de datos para la prestación de los servicios turísticos atendiendo a los cambios que se van generando. 5. Diseñar, dirigir, efectuar y controlar planes, programas y proyectos de comercialización, mediante la implementación de estrategias de comercialización, de comunicación, promoción y publicidad. 6. Generar proyectos que reconozcan la naturaleza social y económica de los fenómenos turísticos y sus variaciones en el tiempo y el espacio, con el fin de preservar y conservar el ambiente.</p>